## Step 0 — Imports

In [1]:
import os
import pymysql
import pandas as pd

RAW_DIR = "data"
CLEAN_DIR = "data/cleaned"
#DB_PATH = "tmdb.db"

os.makedirs(CLEAN_DIR, exist_ok=True)

In [2]:
import psycopg2

## Step 1 — Load the raw CSVs

Load all six files into separate DataFrames and take a first look at their
size. This is just a sanity check — confirming nothing failed to load and
the row counts roughly match what you collected.

In [3]:
movies = pd.read_csv(f"{RAW_DIR}/movies.csv")
genres = pd.read_csv(f"{RAW_DIR}/genres.csv")
movie_genres = pd.read_csv(f"{RAW_DIR}/movie_genres.csv")
cast = pd.read_csv(f"{RAW_DIR}/cast.csv")
crew = pd.read_csv(f"{RAW_DIR}/crew.csv")
movie_keywords = pd.read_csv(f"{RAW_DIR}/movie_keywords.csv")

for name, df in [("movies", movies), ("genres", genres), ("movie_genres", movie_genres),
                  ("cast", cast), ("crew", crew), ("movie_keywords", movie_keywords)]:
    print(f"{name:<15} {len(df):>7} rows, {len(df.columns)} columns")

movies             2509 rows, 12 columns
genres               19 rows, 2 columns
movie_genres       6888 rows, 2 columns
cast              24917 rows, 6 columns
crew               7297 rows, 6 columns
movie_keywords    41701 rows, 3 columns

## Step 2 — Inspect the `movies` table

In [4]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   str
 2   original_language  2509 non-null   str
 3   release_date       2509 non-null   str
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   str
 11  overview           2509 non-null   str
dtypes: float64(4), int64(3), str(5)
memory usage: 235.3 KB

In [5]:
movies.isnull().sum()

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

## Step 3 — Clean the `movies` table

Four things to fix here:
1. **Duplicate rows** — drop any exact duplicate `movie_id` (shouldn't exist, but always check).
2. **`release_date`** — currently a plain string; convert it to an actual date type so it can be filtered/sorted properly.
3. **Numeric columns** — `runtime`, `budget`, `revenue`, `vote_count`, `popularity`, `vote_average` should all be numbers, not text.
4. **Rows with no title** — a movie with a missing title is unusable, so we drop those.

**Note:** we are *deliberately not* touching `budget`/`revenue` values that
are `0` here. TMDB uses `0` to mean "this figure is unknown" — not "this
movie was free." Deciding how to handle that is one of your Pandas
analysis questions later, so we leave it untouched for now.

In [6]:
before = len(movies)
movies = movies.drop_duplicates(subset="movie_id")
print(f"Dropped {before - len(movies)} duplicate movie rows.")

Dropped 6 duplicate movie rows.

In [7]:
movies["release_date"] = pd.to_datetime(movies["release_date"], errors="coerce")
movies["release_date"].head()

0   2014-11-05
1   2010-07-15
2   2012-04-25
3   2008-07-16
4   2009-12-16
Name: release_date, dtype: datetime64[us]

In [8]:
numeric_cols = ["runtime", "budget", "revenue", "vote_count", "popularity", "vote_average"]
for col in numeric_cols:
    movies[col] = pd.to_numeric(movies[col], errors="coerce")

movies[numeric_cols].dtypes

runtime           int64
budget          float64
revenue         float64
vote_count        int64
popularity      float64
vote_average    float64
dtype: object

In [9]:
before = len(movies)
movies = movies.dropna(subset=["movie_id", "title"])
print(f"Dropped {before - len(movies)} rows with a missing title.")
print(f"movies table now has {len(movies)} rows.")

Dropped 0 rows with a missing title.
movies table now has 2503 rows.

## Step 4 — Clean the `genres` table

This is a small static reference table — just remove duplicates and any
row missing an ID or name.

In [10]:
before = len(genres)
genres = genres.drop_duplicates(subset="genre_id").dropna(subset=["genre_id", "genre_name"])
print(f"genres: {before} -> {len(genres)} rows")
genres.head()

genres: 19 -> 19 rows

   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

## Step 5 — Clean the `movie_genres` bridge table

This table links movies to genres. The important check here isn't just
duplicates — it's **referential integrity**: every `movie_id` here should
exist in the cleaned `movies` table, and every `genre_id` should exist in
the cleaned `genres` table. If a movie got dropped in Step 3 (e.g., for
having no title), any bridge rows pointing to it are now orphaned and
should be removed too.

In [11]:
before = len(movie_genres)
movie_genres = movie_genres.drop_duplicates()
movie_genres = movie_genres[movie_genres["movie_id"].isin(movies["movie_id"])]
movie_genres = movie_genres[movie_genres["genre_id"].isin(genres["genre_id"])]
print(f"movie_genres: {before} -> {len(movie_genres)} rows")

movie_genres: 6888 -> 6878 rows

## Step 6 — Clean the `cast` table

Same idea: drop duplicates, drop rows with no actor name, and drop any row
pointing to a `movie_id` that no longer exists in `movies`.

In [12]:
before = len(cast)
cast = cast.drop_duplicates(subset="cast_row_id").dropna(subset=["actor_name"])
cast = cast[cast["movie_id"].isin(movies["movie_id"])]
print(f"cast: {before} -> {len(cast)} rows")

cast: 24917 -> 24902 rows

## Step 7 — Clean the `crew` table

Same pattern as `cast`, applied to directors/writers.

In [13]:
before = len(crew)
crew = crew.drop_duplicates(subset="crew_row_id").dropna(subset=["person_name"])
crew = crew[crew["movie_id"].isin(movies["movie_id"])]
print(f"crew: {before} -> {len(crew)} rows")

crew: 7297 -> 7289 rows

## Step 8 — Clean the `movie_keywords` table

Same pattern again.

In [14]:
before = len(movie_keywords)
movie_keywords = movie_keywords.drop_duplicates().dropna(subset=["keyword_name"])
movie_keywords = movie_keywords[movie_keywords["movie_id"].isin(movies["movie_id"])]
print(f"movie_keywords: {before} -> {len(movie_keywords)} rows")

movie_keywords: 41701 -> 41681 rows

## Step 9 — Save the cleaned tables

Save each cleaned DataFrame to `data/cleaned/` as a checkpoint, separate
from the original raw files. This way you always still have the untouched
raw data if you ever need to redo a cleaning decision differently.

In [15]:
cleaned_tables = {
    "movies": movies,
    "genres": genres,
    "movie_genres": movie_genres,
    "cast": cast,
    "crew": crew,
    "movie_keywords": movie_keywords,
}

for name, df in cleaned_tables.items():
    path = f"{CLEAN_DIR}/{name}.csv"
    df.to_csv(path, index=False)
    print(f"Saved {path} ({len(df)} rows)")

Saved data/cleaned/movies.csv (2503 rows)
Saved data/cleaned/genres.csv (19 rows)
Saved data/cleaned/movie_genres.csv (6878 rows)
Saved data/cleaned/cast.csv (24902 rows)
Saved data/cleaned/crew.csv (7289 rows)
Saved data/cleaned/movie_keywords.csv (41681 rows)

## Step 10 — Load the cleaned tables into SQLite

SQLite is the simplest database to start with — it's just a single file
(`tmdb.db`), no server setup required. `pandas.DataFrame.to_sql()` creates
the table and inserts all rows in one call.

(If you'd rather use MySQL or PostgreSQL instead, swap this connection for
one made with `pymysql`/`mysql-connector-python` or `psycopg2` — everything
else in this notebook stays the same.)

In [21]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hai\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.8 MB/s eta 0:00:00
Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl (247 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.5.4 sqlalchemy-2.0.51

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:1234@localhost/tmdb")  # Replace with your MySQL credentials

for name, df in cleaned_tables.items():
    df.to_sql(name, engine, if_exists="replace", index=False)
    print(f"Loaded table '{name}' ({len(df)} rows) into MySQL database 'tmdb'.")


print("\nAll tables loaded into MySQL.")

Loaded table 'movies' (2499 rows) into MySQL database 'tmdb'.
Loaded table 'genres' (19 rows) into MySQL database 'tmdb'.
Loaded table 'movie_genres' (6878 rows) into MySQL database 'tmdb'.
Loaded table 'cast' (24902 rows) into MySQL database 'tmdb'.
Loaded table 'crew' (7289 rows) into MySQL database 'tmdb'.
Loaded table 'movie_keywords' (41681 rows) into MySQL database 'tmdb'.

All tables loaded into MySQL.

In [20]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:1234@localhost/tmdb")  # Replace with your PostgreSQL credentials

for name, df in cleaned_tables.items():
    df.to_sql(name, engine, if_exists="replace", index=False)
    print(f"Loaded table '{name}' ({len(df)} rows) into PostgreSQL database 'tmdb'.")


print("\nAll tables loaded into PostgreSQL.")

Loaded table 'movies' (2499 rows) into PostgreSQL database 'tmdb'.
Loaded table 'genres' (19 rows) into PostgreSQL database 'tmdb'.
Loaded table 'movie_genres' (6878 rows) into PostgreSQL database 'tmdb'.
Loaded table 'cast' (24902 rows) into PostgreSQL database 'tmdb'.
Loaded table 'crew' (7289 rows) into PostgreSQL database 'tmdb'.
Loaded table 'movie_keywords' (41681 rows) into PostgreSQL database 'tmdb'.

All tables loaded into PostgreSQL.

## Step 11 — Test query

One quick JOIN across `movies`, `movie_genres` and `genres` to confirm the
database actually works end-to-end before moving on to the full SQL
analysis notebook.

In [23]:


query = """
    SELECT m.title, m.release_date, m.revenue, g.genre_name
    FROM movies m
    JOIN movie_genres mg ON m.movie_id = mg.movie_id
    JOIN genres g ON mg.genre_id = g.genre_id
    WHERE g.genre_name = 'Action'
    ORDER BY m.revenue DESC
    LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

                          title release_date     revenue genre_name
0                        Avatar   2009-12-16  2923706026     Action
1             Avengers: Endgame   2019-04-24  2799439100     Action
2      Avatar: The Way of Water   2022-12-14  2334484620     Action
3  Star Wars: The Force Awakens   2015-12-15  2068223624     Action
4        Avengers: Infinity War   2018-04-25  2052415039     Action